export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const PLAY = 'PLAY';
export const SHOW_CARDS = 'SHOW_CARDS';
export const GENERAL_SCORE = 'GENERAL_SCORE';
export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';